<?php
class MewBinWAF_Config {
    
    public static $security = [
        'max_requests_per_minute' => 30,
        'max_requests_per_hour' => 500,
        'max_accounts_per_hour' => 2,
        'max_failed_logins' => 3,
        'block_duration' => 60,
        'permanent_ban_threshold' => 10
    ];

    public static $patterns = [
        '/union[\s\S]{1,100}select/i',
        '/insert[\s\S]{1,100}into/i',
        '/update[\s\S]{1,100}set/i',
        '/delete[\s\S]{1,100}from/i',
        '/drop[\s\S]{1,100}(table|database)/i',
        '/exec(\s|\()/i',
        '/xp_cmdshell/i',
        '/load_file/i',
        '/outfile|dumpfile/i',
        '/benchmark\s*\(/i',
        '/sleep\s*\(/i',
        '/waitfor\s+delay/i',
        '/shutdown/i',
        '/--[\s\S]*$/m',
        '/\/\*[\s\S]*\*\//m',
        '/;\s*(drop|delete|update|insert)/i',
        '/<script[^>]*>/i',
        '/javascript:/i',
        '/vbscript:/i',
        '/on\w+\s*=/i',
        '/alert\s*\(/i',
        '/document\./i',
        '/window\./i',
        '/eval\s*\(/i',
        '/setTimeout\s*\(/i',
        '/Function\s*\(/i',
        '/\.\.\//',
        '/\.\.\\\/',
        '/etc\/passwd/i',
        '/proc\/self/i',
        '/\/bin\/(sh|bash)/i',
        '/\|\s*\w+/',
        '/;\s*\w+/',
        '/`\s*\w+/',
        '/\$\s*\(/',
        '/base64_decode/i',
        '/gzinflate/i',
        '/eval\s*\(\s*base64_decode/i',
        '/system\s*\(/i',
        '/exec\s*\(/i',
        '/shell_exec\s*\(/i',
        '/passthru\s*\(/i',
        '/proc_open/i',
        '/php:\/\//i',
        '/data:\/\//i',
        '/expect:\/\//i',
        '/\b(and|or)\b\s+[\d\w]\s*=\s*[\d\w]/i',
        '/order\s+by\s+[\d+]/i',
        '/into\s+(outfile|dumpfile)/i',
        '/0x[0-9a-f]+/i',
        '/char\s*\(/i',
        '/@@version/i',
        '/user\s*\(/i',
        '/information_schema/i',
        '/mysql\./i',
        '/\b(XMLHttpRequest|ActiveXObject|fetch)\b/i',
        '/\b(FileReader|Blob)\b/i',
        '/\b(WebRTC|RTCPeerConnection)\b/i',
        '/\b(ServiceWorker|Worker)\b/i',
        '/\b(crypto|getRandomValues)\b/i',
        '/\b(geolocation|GPS)\b/i',
        '/\b(device|orientation)\b/i',
        '/\b(bluetooth|nfc)\b/i',
        '/\b(gps|location)\b/i',
        '/\b(network|connection)\b/i',
        '/\b(ip|mac)\b/i',
        '/\b(http|https|ftp)\b.*(get|post)/i',
        '/\b(ws|wss)\b/i',
        '/\b(eval|setTimeout)\b/i',
        '/\b(localStorage|sessionStorage)\b/i',
        '/\b(cookie|indexedDB)\b/i',
        '/\b(history|pushState)\b/i',
        '/\b(beforeunload|unload)\b/i',
        '/\b(mouse|click)\b/i',
        '/\b(key|keydown)\b/i',
        '/\b(touch|gesture)\b/i',
        '/\b(input|change)\b/i',
        '/\b(load|error)\b/i',
        '/\b(online|offline)\b/i',
        '/\b(install|activate)\b/i',
        '/\b(notification|permission)\b/i',
        '/\b(clipboard|copy)\b/i',
        '/\b(cache|storage)\b/i',
        '/\b(applicationCache)\b/i',
        '/\b(serviceWorker)\b/i',
        '/\b(webworker)\b/i',
        '/\b(pwa)\b/i',
        '/\b(manifest)\b/i',
        '/\b(install)\b/i',
        '/\b(webapk)\b/i',
        '/\b(notification)\b/i',
        '/\b(push)\b/i',
        '/\b(background)\b/i',
        '/\b(suspend)\b/i',
        '/\b(resume)\b/i',
        '/\b(memory)\b/i',
        '/\b(heap)\b/i',
        '/\b(cpu)\b/i',
        '/\b(processor)\b/i',
        '/\b(gpu)\b/i',
        '/\b(storage)\b/i',
        '/\b(battery)\b/i',
        '/\b(power)\b/i',
        '/\b(thermal)\b/i',
        '/\b(temperature)\b/i',
        '/\b(volume)\b/i',
        '/\b(play)\b/i',
        '/\b(pause)\b/i',
        '/\b(crossorigin)\b/i',
        '/\b(anonymous)\b/i',
        '/\b(referrer)\b/i',
        '/\b(integrity)\b/i',
        '/\b(csp)\b/i',
        '/\b(content-security-policy)\b/i',
        '/\b(hsts)\b/i',
        '/\b(xss)\b/i',
        '/\b(x-frame-options)\b/i',
        '/\b(feature-policy)\b/i',
        '/\b(permissions-policy)\b/i',
        '/\b(upgrade-insecure-requests)\b/i',
        '/\b(wasm)\b/i',
        '/\b(webassembly)\b/i',
        '/\b(emscripten)\b/i',
        '/\b(vr|ar|mr)\b/i',
        '/\b(webxr|webvr)\b/i',
        '/\b(sensor)\b/i',
        '/\b(accelerometer)\b/i',
        '/\b(gyroscope)\b/i',
        '/\b(magnetometer)\b/i',
        '/\b(compass)\b/i',
        '/\b(ambient)\b/i',
        '/\b(light)\b/i',
        '/\b(proximity)\b/i',
        '/\b(heart)\b/i',
        '/\b(rate)\b/i',
        '/\b(bluetooth)\b/i',
        '/\b(ble)\b/i',
        '/\b(nfc)\b/i',
        '/\b(wifi)\b/i',
        '/\b(cellular)\b/i',
        '/\b(gps)\b/i',
        '/\b(port)\b/i',
        '/\b(socket)\b/i',
        '/\b(tcp)\b/i',
        '/\b(udp)\b/i',
        '/\b(dns)\b/i',
        '/\b(domain)\b/i',
        '/\b(websocket)\b/i',
        '/\b(webrtc)\b/i',
        '/\b(rtcpeerconnection)\b/i',
        '/\b(stream)\b/i',
        '/\b(track)\b/i',
        '/\b(codec)\b/i',
        '/\b(encoder)\b/i',
        '/\b(latency)\b/i',
        '/\b(jitter)\b/i',
        '/\b(packet)\b/i',
        '/\b(bandwidth)\b/i',
        '/\b(throughput)\b/i',
        '/\b(buffer)\b/i',
        '/\b(cache)\b/i',
        '/\b(memory)\b/i',
        '/\b(heap)\b/i',
        '/\b(stack)\b/i',
        '/\b(pointer)\b/i',
        '/\b(malloc)\b/i',
        '/\b(free)\b/i',
        '/\b(garbage)\b/i',
        '/\b(leak)\b/i',
        '/\b(overflow)\b/i',
        '/\b(underflow)\b/i',
        '/\b(race)\b/i',
        '/\b(condition)\b/i',
        '/\b(deadlock)\b/i',
        '/\b(semaphore)\b/i',
        '/\b(mutex)\b/i',
        '/\b(lock)\b/i',
        '/\b(thread)\b/i',
        '/\b(process)\b/i',
        '/\b(async)\b/i',
        '/\b(await)\b/i',
        '/\b(promise)\b/i',
        '/\b(observable)\b/i',
        '/\b(hash)\b/i',
        '/\b(map)\b/i',
        '/\b(set)\b/i',
        '/\b(list)\b/i',
        '/\b(array)\b/i',
        '/\b(tree)\b/i',
        '/\b(graph)\b/i',
        '/\b(stack)\b/i',
        '/\b(queue)\b/i',
        '/\b(heap)\b/i',
        '/\b(linked-list)\b/i',
        '/\b(binary)\b/i',
        '/\b(avl)\b/i',
        '/\b(red-black)\b/i',
        '/\b(b-tree)\b/i',
        '/\b(trie)\b/i',
        '/\b(bloom)\b/i',
        '/\b(filter)\b/i',
        '/\b(sketch)\b/i',
        '/\b(quantile)\b/i',
        '/\b(histogram)\b/i',
        '/\b(distribution)\b/i',
        '/\b(mean)\b/i',
        '/\b(median)\b/i',
        '/\b(variance)\b/i',
        '/\b(correlation)\b/i',
        '/\b(regression)\b/i',
        '/\b(clustering)\b/i',
        '/\b(encoding)\b/i',
        '/\b(decoding)\b/i',
        '/\b(embedding)\b/i',
        '/\b(vector)\b/i',
        '/\b(similarity)\b/i',
        '/\b(distance)\b/i',
        '/\b(euclidean)\b/i',
        '/\b(manhattan)\b/i',
        '/\b(cosine)\b/i',
        '/\b(jaccard)\b/i',
        '/\b(hamming)\b/i',
        '/\b(levenshtein)\b/i',
        '/\b(pearson)\b/i',
        '/\b(spearman)\b/i',
        '/\b(entropy)\b/i',
        '/\b(cross-entropy)\b/i',
        '/\b(chi-square)\b/i',
        '/\b(fisher)\b/i',
        '/\b(t-test)\b/i',
        '/\b(anova)\b/i',
        '/\b(kolmogorov-smirnov)\b/i',
        '/\b(shapiro-wilk)\b/i'
    ];

    public static $suspicious_user_agents = [
        'sqlmap', 'nmap', 'metasploit', 'burpsuite', 'nikto',
        'w3af', 'acunetix', 'appscan', 'nessus', 'openvas',
        'havij', 'zap', 'dirbuster', 'gobuster', 'wfuzz',
        'hydra', 'medusa', 'patator', 'crowbar', 'thc-hydra',
        'aircrack', 'reaver', 'bully', 'pyrit', 'cowpatty',
        'kismet', 'wireshark', 'tshark', 'tcpdump', 'ncat',
        'netcat', 'socat', 'curl', 'wget', 'python-requests',
        'python-urllib', 'go-http-client', 'java', 'perl',
        'ruby', 'lwp', 'mechanize', 'phantomjs', 'slimerjs',
        'casperjs', 'nightmare', 'puppeteer', 'playwright',
        'selenium', 'webdriver', 'chromedriver', 'geckodriver',
        'iedriver', 'safaridriver', 'appium', 'robotframework',
        'testcafe', 'cypress', 'protractor', 'karma', 'jasmine',
        'mocha', 'jest', 'ava', 'tape', 'qunit', 'enzyme',
        'sinon', 'chai', 'should', 'expect', 'assert',
        'powerassert', 'unexpected', 'proxy', 'vpn', 'tor',
        'anonymizer', 'shield', 'guard', 'firewall', 'ips',
        'ids', 'waf', 'scanner', 'crawler', 'spider', 'bot'
    ];

    public static $whitelisted_ips = [
        '127.0.0.1',
        '::1'
    ];

    public static $blacklisted_ips = [
    ];

    public static $protected_pages = [
        'register.php',
        'login.php',
        'post.php',
        'adminpanel/',
        'settings.php',
        'user/',
        'messages.php'
    ];

    public static $high_risk_pages = [
        'adminpanel/',
        'settings.php',
        'user/profile'
    ];

    public static $logging = [
        'enabled' => true,
        'log_file' => 'waf_security.log',
        'max_log_size' => 10485760,
        'log_level' => 'HIGH'
    ];

    public static $advanced_protection = [
        'block_tor_nodes' => false,
        'block_proxies' => false,
        'block_vpns' => false,
        'detect_bots' => true,
        'prevent_clickjacking' => true,
        'prevent_mime_sniffing' => true,
        'enable_hsts' => true,
        'enable_csp' => true,
        'block_hotlinking' => true,
        'prevent_ddos' => true
    ];

    public static $headers_protection = [
        'X-Frame-Options' => 'DENY',
        'X-Content-Type-Options' => 'nosniff',
        'X-XSS-Protection' => '1; mode=block',
        'Strict-Transport-Security' => 'max-age=31536000; includeSubDomains',
        'Referrer-Policy' => 'strict-origin-when-cross-origin',
        'Content-Security-Policy' => "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none';"
    ];
}
?>
[file content end]